name: Branch Build

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rust Nightly
      run: rustup toolchain install nightly
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
    - name: Format code & commit
      run: |
        cargo +nightly fmt
        git config --global user.name 'Bot'
        git config --global user.email 'mikekap@users.noreply.github.com'
        if [[ -n "$(git status --porcelain)" ]]; then
          git commit -am "Format code"
          git push
        fi
