name: Branch Build

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rust Nightly
      run: rustup toolchain install nightly && rustup component add rustfmt --toolchain nightly
    - uses: actions/checkout@v2
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
    - name: Formatted code
      run: |
        cargo +nightly fmt
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Your code is not formatted - please run cargo +nightly fmt";
          exit 1;
        fi
